### ISSUE TITLE
Input File

### ISSUE THREAD

**Issue by TimMcDowell** [JasonGlazer/ashrae-140-automation#44]
The input uses the informative RESULTS5-2A.xlsx with all of the tables and charts rather than the simpler normative Sec5-2Aout.xlsx.

**Comment by JasonGlazer** [comment]
I think this was addressed in:

https://github.com/JasonGlazer/ashrae-140-automation/pull/51

I used the 140-2023 file naming: std140_tf_output.xlsx, etc..

**Comment by JasonGlazer** [comment]
I think I addressed the rest of the file naming issue in #52.

If there was something else that you saw. Please let me know or post another issue.
