### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by TimMcDowell** [JasonGlazer/ashrae-140-automation#46]
The names of the spreadsheets are changing with the 2023 release. Maybe using a YAML file to collect file names of the spreadsheets would make this more universal.

**Comment by JasonGlazer** [comment]
@TimMcDowell I made some of the changes to the file naming here:

https://github.com/JasonGlazer/ashrae-140-automation/pull/51

**Comment by JasonGlazer** [comment]
Finished in #52
